### ISSUE TITLE
Any problem with second git assignment?

### ISSUE THREAD

**Issue by YoannDupont** [Elesionore/PPE1-2023-etudiante#1]
Greetings,

I see you use English in your commits, so I'll use it in this issue.

There seem to be missing some git exercices. Did you encounter any problem with git commands seen last week? You should mention it in the journal if you do. You can also create an issue just like this one if you need some help.

Best.

**Comment by Elesionore** [comment]
Non, enfin ça va :) 
J'avais du problème avec commit, mais puis j'ai ajouté un paramètre -a et ça marche

**Comment by Elesionore** [comment]
Excusez-moi pour le mélange de l'anglais et du français, j'écris chaotiquement et change la langue souvent

**Comment by YoannDupont** [comment]
Si tout va bien, je ferme l'issue dans ce cas !
